{
 "title": "pfSense Plus",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "Host",
    "label": "pfSense",
    "query": "SHOW TAG VALUES FROM \"pf\" WITH KEY = \"host\""
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\" WHERE \"host\" =~ /^$Host$/"
   },
   {
    "name": "Gateway",
    "query": "SHOW TAG VALUES FROM \"gateways\" WITH KEY = \"gateway_name\" WHERE \"host\" =~ /^$Host$/ "
   },
   { "name": "WAN", "query": "igb0,ovpnc1" },
   {
    "name": "LAN_Interfaces",
    "label": "LAN",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" =~ /^$Host$/ "
   },
   {
    "name": "CPU",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE \"host\" =~ /^$Host$/ and cpu !~ /cpu-total/"
   },
   {
    "name": "Sensor",
    "query": "SHOW TAG VALUES FROM \"temperature\" WITH KEY = \"sensor\" WHERE \"host\" =~ /^$Host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_users\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"pfSense\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Uso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu0\" or r[\"cpu\"] == \"cpu1\" or r[\"cpu\"] == \"cpu2\" or r[\"cpu\"] == \"cpu3\" or r[\"cpu\"] == \"cpu4\" or r[\"cpu\"] == \"cpu5\" or r[\"cpu\"] == \"cpu6\" or r[\"cpu\"] == \"cpu7\")\r\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$CPU$/" }
     ]
    }
   ]
  },
  {
   "title": "Carga CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load5\" or r[\"_field\"] == \"load15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"pfSense\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"host\"] == \"pfSense\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ram Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SWAP Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ram Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SWAP Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"swap\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ram Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SWAP Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disco Uso",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "devfs" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disco I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"pfSense\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\" or r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vtbd0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "devfs" },
      { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$Disk$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN - vtnet0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAN - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet0\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "LAN - vtnet1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "LAN vtnet1 - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN vtnet1 - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN vtnet1 - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN vtnet1 - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN vtnet1 - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "LAN - Gestión - vtnet1.10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "LAN - Gestión - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.10\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Gestión - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.10\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Gestión - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.10\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Gestión - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.10\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Gestión - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.10\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "LAN - Principal - vtnet1.11", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "LAN - Principal - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.11\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Principal - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.11\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Principal - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.11\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Principal - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.11\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Principal - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.11\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "LAN - SmartHome - vtnet1.13", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "LAN - SmartHome - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.13\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - SmartHome - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.13\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - SmartHome - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.13\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - SmartHome - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.13\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - SmartHome - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.13\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "LAN - Invitados - vtnet1.15", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "LAN - Invitados - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.15\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Invitados - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.15\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Invitados - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.15\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Invitados - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "LAN - Invitados - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"vtnet1.15\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "WireGuard - Servidor - tun_wg0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "WG - Servidor - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Servidor - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg0\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Servidor - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg0\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Servidor - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Servidor - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "WireGuard - Cliente - tun_wg1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "WG - Cliente - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg1\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg1\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "WireGuard - Cliente - tun_wg2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "WG - Cliente - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg2\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Tráfico",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg2\")\r\n  |> derivative(unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "WG - Cliente - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"tun_wg2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "OpenVPN - Servidor - ovpns1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "OpenVPN - Servidor - Velocidad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"ovpns1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_recv\") / count(\"bytes_recv\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Recv" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "1s" ], "type": "derivative" },
       {
        "params": [
         "* count(\"bytes_sent\") / count(\"bytes_sent\")"
        ],
        "type": "math"
       },
       { "params": [ "Bytes_Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$WAN$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenVPN - Servidor - Paquetes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\" or r[\"_field\"] == \"packets_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"ovpns1\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenVPN - Servidor - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"ovpns1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenVPN - Servidor - Tráfico Acumulado",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"ovpns1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenVPN - Servidor - ERR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface - $col",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "from(bucket: \"PFSENSE\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"err_in\" or r[\"_field\"] == \"err_out\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"ovpns1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       { "params": [ "Drop_In" ], "type": "alias" }
      ],
      [
       { "params": [ "drop_out" ], "type": "field" },
       { "params": [ "Drop_Out" ], "type": "alias" }
      ],
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "Err_In" ], "type": "alias" }
      ],
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "Err_Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$WAN$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}