{
 "title": "QNAP TVS-h1288X",
 "description": "Grafana Dashboard para el QNAP TVS-h1288X. Recoge los datos Telegraf y los envía al InfluxDB",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "qnaphostname",
    "label": "Hostname",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP.enclosureTable\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] != \"\")\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()\r\n  \r\n"
   },
   {
    "name": "qnapmodel",
    "label": "QNAP",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP.enclosureTable\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enclosureSerialNum\" and  r[\"enclosureID\"] == \"0\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${qnaphostname:regex}/)\r\n  |> keep(columns: [\"enclosureModel\"])\r\n  |> distinct(column: \"enclosureModel\")\r\n  |> group()\r\n  \r\n"
   },
   {
    "name": "qnapdisk",
    "label": "Disk",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP.diskTable\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${qnaphostname:regex}/)\r\n  |> keep(columns: [\"diskID\"])\r\n  |> distinct(column: \"diskID\")\r\n  |> group()\r\n  \r\n"
   }
  ]
 },
 "panels": [
  { "title": "QNAP TVS-h1288X", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tiempo Encendido",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/100", "type": "math" }
   ]
  },
  {
   "title": "Firmware Actual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"firmware_version_actual\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "¿Hay Actualización?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"firmware_version_nueva\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "SAI - Modelo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups_modelo\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "SAI - Potencia Actual W%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups_carga_porcentaje\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "SAI - Carga Batería %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load 15m",
     "measurement": "system",
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ups_carga_bateria\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  { "title": "Estado general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Uso",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_uso\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RAM Uso",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"memoria_ram_usada\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Ventiladores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 13 },
   "repeat": "qnaphostname",
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm_ventilador_1\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm_ventilador_2\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rpm_ventilador_3\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 13 },
   "repeat": "qnaphostname",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_cpu\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura_sistema\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturas SSD",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 18 },
   "repeat": "qnaphostname",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_1\" or r[\"_field\"] == \"disco_modelo_1\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_2\" or r[\"_field\"] == \"disco_modelo_2\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_3\" or r[\"_field\"] == \"disco_modelo_3\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_4\" or r[\"_field\"] == \"disco_modelo_4\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas Discos Duros",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_5\" or r[\"_field\"] == \"disco_modelo_5\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_6\" or r[\"_field\"] == \"disco_modelo_6\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_7\" or r[\"_field\"] == \"disco_modelo_7\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_8\" or r[\"_field\"] == \"disco_modelo_8\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_9\" or r[\"_field\"] == \"disco_modelo_9\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_10\" or r[\"_field\"] == \"disco_modelo_10\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas SSD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_1\" or r[\"_field\"] == \"disco_modelo_1\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_2\" or r[\"_field\"] == \"disco_modelo_2\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_3\" or r[\"_field\"] == \"disco_modelo_3\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_4\" or r[\"_field\"] == \"disco_modelo_4\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperaturas Discos Duros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_5\" or r[\"_field\"] == \"disco_modelo_5\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_6\" or r[\"_field\"] == \"disco_modelo_6\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_7\" or r[\"_field\"] == \"disco_modelo_7\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_8\" or r[\"_field\"] == \"disco_modelo_8\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_9\" or r[\"_field\"] == \"disco_modelo_9\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disco_temperatura_10\" or r[\"_field\"] == \"disco_modelo_10\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Uso Almacenamiento", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Conjunto de Almacenamiento 1 (NVMe)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_1_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_1_espacio_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Conjuntos Almacenamiento %",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_1_espacio_disponible\" or r[\"_field\"] == \"conjunto_almacenamiento_1_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.conjunto_almacenamiento_1_espacio_disponible) / float(v: r.conjunto_almacenamiento_1_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_2_espacio_disponible\" or r[\"_field\"] == \"conjunto_almacenamiento_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.conjunto_almacenamiento_2_espacio_disponible) / float(v: r.conjunto_almacenamiento_2_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Conjunto de Almacenamiento 2 (HDD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$C-$D", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_2_espacio_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Conjuntos Almacenamiento %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_1_espacio_disponible\" or r[\"_field\"] == \"conjunto_almacenamiento_1_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.conjunto_almacenamiento_1_espacio_disponible) / float(v: r.conjunto_almacenamiento_1_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"conjunto_almacenamiento_2_espacio_disponible\" or r[\"_field\"] == \"conjunto_almacenamiento_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.conjunto_almacenamiento_2_espacio_disponible) / float(v: r.conjunto_almacenamiento_2_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_2_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS %",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_2_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_2_capacidad_disponible) / float(v: r.carpeta_compartida_2_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_3_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_3_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_3_capacidad_disponible) / float(v: r.carpeta_compartida_3_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_4_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_4_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_4_capacidad_disponible) / float(v: r.carpeta_compartida_4_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - Almacén",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_3_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_3_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - BitTorrent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_4_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_4_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_2_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_2_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_2_capacidad_disponible) / float(v: r.carpeta_compartida_2_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_3_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_3_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_3_capacidad_disponible) / float(v: r.carpeta_compartida_3_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_4_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_4_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_4_capacidad_disponible) / float(v: r.carpeta_compartida_4_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - Copias Seguridad",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_5_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_5_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS %",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_5_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_5_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_5_capacidad_disponible) / float(v: r.carpeta_compartida_5_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_6_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_6_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_6_capacidad_disponible) / float(v: r.carpeta_compartida_6_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_7_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_7_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_7_capacidad_disponible) / float(v: r.carpeta_compartida_7_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - Multimedia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_6_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_6_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS - QVR Elite",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_7_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    { "expression": "$A-$B", "type": "math" },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_7_capacidad_disponible\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ZFS %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_5_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_5_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_5_capacidad_disponible) / float(v: r.carpeta_compartida_5_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_6_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_6_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_6_capacidad_disponible) / float(v: r.carpeta_compartida_6_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"QNAPTVSh1288X\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.QNAP_TVS-h1288X\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"carpeta_compartida_7_capacidad_disponible\" or r[\"_field\"] == \"carpeta_compartida_7_capacidad_total\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.10.2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"qnaptvsh1288x\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: 100.0 - (float(v: r.carpeta_compartida_7_capacidad_disponible) / float(v: r.carpeta_compartida_7_capacidad_total) * 100.0) }))\r\n  |> group(columns: [\"source\",\"_field\",\"agent_host\"])\r\n  |> aggregateWindow(every: ${interval}, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}